name: Build Docker Base

on: 
  workflow_dispatch

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build Focal" ]
        include:
        
          - name: "Build Focal"
            release: focal
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Get Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push base
        id: docker_build_base
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/${{ matrix.release }}/base/Dockerfile
          push: true
          tags: terraferma/base:${{ env.name }}-${{ matrix.release }}

      - name: Build and push base amd64
        id: docker_build_base_amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: docker/${{ matrix.release }}/base/Dockerfile
          push: true
          tags: terraferma/base:${{ env.name }}-${{ matrix.release }}-amd64

      - name: Build and push base arm64
        id: docker_build_base_arm64
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          file: docker/${{ matrix.release }}/base/Dockerfile
          push: true
          tags: terraferma/base:${{ env.name }}-${{ matrix.release }}-arm64
