name: Build Docker

on:
  workflow_dispatch
  push:
    - 'multiplatform-actions'

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build Focal" ]
        include:
        
          - name: "Build Focal"
            release: focal
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Get Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push base
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/${{ matrix.release }}/base/Dockerfile
          push: true
          tags: terraferma/base:${{ env.name }}-${{ matrix.release }}

      - name: Build and push dev-env
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-arg: TAG=${{ env.name }}-${{ matrix.release }}
          file: docker/${{ matrix.release }}/dev-env/Dockerfile
          push: true
          tags: terraferma/dev-env:${{ env.name }}-${{ matrix.release }}

